server:
  port: ${sealtalk-config.server_port}
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:             #解决中文乱码问题，同一使用UTF-8编码
      charset: UTF-8
      force: true
      enabled: true
      force-request: true
      force-response: true
  shutdown: graceful      # 优雅停机 ，kill -2 或post请求/actuator/shutdown，不能使用kill -9

spring:

  flyway:
    enabled: false              #flyway 是否启用开关，true启用，false禁用
    # 禁止清理数据库表
    clean-disabled: true
    baseline-description: baselines
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    baseline-version: 2

  swagger2:
    enabled: false
mybatis:
  mapper-locations: classpath:mybatis/*.xml

logging:
  config: classpath:logback-config.xml


sealtalk:
  datasource:
    driverclassname: com.mysql.jdbc.Driver
    url: jdbc:mysql://${sealtalk-config.db_host}:${sealtalk-config.db_port}/${sealtalk-config.db_name}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&useCompress=true
    username: ${sealtalk-config.db_user}
    password: ${sealtalk-config.db_password}
    maximum-pool-size: 20


sealtalk-config:
  auth_cookie_name: rong_im_auth
  auth_cookie_key: ef98re9823434in
  nickname_cookie_name:           # 此字段废弃
  auth_cookie_max_age: 8640000    #  auth_cookie有效期单位秒 8640000=100天
  rongcloud_sms_register_template_id: 3910922   #短信模版
  config_env: prod                 # dev 调试环境 注册环节不发短信，默认验证码9999
  rongcloud_app_key: n19jmcy59f1q9
  rongcloud_app_secret: CuhqdZMeuLsKj
  rongcloud_api_url: api-cn.ronghub.com  # rongcloud api_url
  rongcloud_default_portrait_url: http://www.rongcloud.cn/images/icon-57.png        #登录注册默认头像地址
  qiniu_access_key: livk5rb3__JZjCtEiMxXpQ8QscLxbNLehwhHySnX
  qiniu_secret_key: ysrYdcDrrF425QNz0pfY9RoafANC6Hni3TIVgjw5
  qiniu_bucket_name: sealtalk-image
  qiniu_bucket_domain: 7xogjk.com1.z0.glb.clouddn.com
  yunpian_api_key: bbdfde0dee2cd3957da7d0f5611f082a
  yunpian_limited_time: 1     #云片发送验证码限制时间单位 1小时
  yunpian_limited_count: 1000   #云片发送验证码次数限制    20次
  n3d_key: 11EdDIauqcim
  auth_cookie_domain: rongcloud.cn
  cors_hosts:  http://web.sealtalk.im
  exclude_url: /misc/demo_square,/misc/latest_update, /user/verify_code_yp_t,/misc/client_version,/misc/mobile_version,/user/login,/user/register,/user/reset_password, /user/send_code, /user/send_code_yp,/user/verify_code, /user/verify_code_yp, /user/delete, /user/get_sms_img_code,/user/check_username_available,/user/check_phone_available,/user/regionlist,/ping
  server_port: 8080
  db_name: sealtalk
  db_user: developer
  db_password: 1234%^&*
  db_host: localhost
  db_port: 3306
